# =============================================================================
# Configuración del Panel phpMyAdmin Standalone
# Uso: init-phpmyadmin.sh mi-pma.conf
# =============================================================================

# Puerto local mapeado en el host para acceder al panel web en desarrollo
PMA_PORT_DEV=8011

# Puerto local mapeado en el host para acceder al panel web en producción
PMA_PORT_PROD=8021

# IP del servidor de producción (opcional)
PROD_SERVER_IP=

# Permitir ingresar cualquier Host en la pantalla de login (1 = Sí, 0 = No)
PMA_ARBITRARY=1

# =============================================================================
# VARIABLES DE DESARROLLO (DEV)
# =============================================================================
# Host de la base de datos MySQL (ej: host.docker.internal, o la IP de tu docker host)
PMA_HOST_DEV=host.docker.internal
# Puerto de la base de datos MySQL a la que conectarse
PMA_DB_PORT_DEV=3316
# Red Docker externa a la que unirse para conectar con el contenedor MySQL
DB_NETWORK_DEV=

# =============================================================================
# VARIABLES DE PRODUCCIÓN (PROD)
# =============================================================================
# Host de la base de datos MySQL (ej: host.docker.internal, o la IP de tu docker host)
PMA_HOST_PROD=host.docker.internal
# Puerto de la base de datos MySQL a la que conectarse
PMA_DB_PORT_PROD=3326
# Red Docker externa a la que unirse para conectar con el contenedor MySQL
DB_NETWORK_PROD=


